### ISSUE TITLE
Integration (no attachment bug)

### ISSUE THREAD

**Issue by slkav** [soulseekah/Gravity-Forms-Digest-Bulk-Reports#21]
Hi guys,

I'm trying to integrate this add on in Wordpress and i'm not sure how to go about it. Any pointers?

Thanks

Sarah

**Comment by soulseekah** [comment]
Have you enabled the plugin and configured it correctly as seen on the screenshot here: https://cloud.githubusercontent.com/assets/1967105/3730465/522cf062-16d2-11e4-8898-c65bb53e5933.png

If so, what is the exact issue?

**Comment by slkav** [comment]
It's the installation part i'm having difficulty with. 

http://cl.ly/image/0I1A2t3w1Z21

Should i be installing the zip file as a plugin or manually adding files to the plugin folder? If so which files should I be using and where should they be going?

Sorry! :/

**Comment by soulseekah** [comment]
Upload this folder https://github.com/soulseekah/Gravity-Forms-Digest-Bulk-Reports/tree/master/gravityforms-digest to /wp-content/plugins/

**Comment by slkav** [comment]
Thank you :D 

On 4 Jun 2015, at 15:45, Gennady Kovshenin <notifications@github.com> wrote:

Upload this folder https://github.com/soulseekah/Gravity-Forms-Digest-Bulk-Reports/tree/master/gravityforms-digest <https://github.com/soulseekah/Gravity-Forms-Digest-Bulk-Reports/tree/master/gravityforms-digest> to /wp-content/plugins/

**Comment by slkav** [comment]
I got that working perfectly thank you. Is there potentially an option to generate a .csv file with the digest?

**Comment by soulseekah** [comment]
Yes, there is. add `define( 'GF_DIGESTS_AS_CSV', true );` to your wp-config.php

**Comment by slkav** [comment]
Ok so I implemented that however, the generated email is as follows:

Report generated at 2015-06-05 11:25:49
Contains entries from 2015-06-05 10:25:32 to 2015-06-05 10:25:32
See CSV attachment

And there is no csv attachment to the email.

**Comment by soulseekah** [comment]
Please set my email as the recipient gennady(at)kovshenin(dot)com and have
it send me a report please.

**Comment by slkav** [comment]
Done.

**Comment by soulseekah** [comment]
Yeh, seems to be coming without an attachment. I'll try to look into it later next week.

**Comment by slkav** [comment]
Thanks a million. 😀

**Comment by slkav** [comment]
Hiya,

I was just wondering if you've had any joy with this yet?

**Comment by slkav** [comment]
Hi. I was just wondering if you've had any luck with the CSV not coming down with the email reports?

**Comment by soulseekah** [comment]
Yeh, I just got an email with a CSV attachment; could it be that attachments are not provided when there are no entries to report?

**Comment by slkav** [comment]
That’s a possibility. I can turn off reports if no entries have been added. That might save some questions. 

Thank you for this. 

On 16 Jun 2015, at 13:45, Gennady Kovshenin <notifications@github.com> wrote:

Yeh, I just got an email with a CSV attachment; could it be that attachments are not provided when there are no entries to report?

**Comment by soulseekah** [comment]
Hmmm, no, I'm reading the code now and seeing https://github.com/soulseekah/Gravity-Forms-Digest-Bulk-Reports/blob/master/gravityforms-digest/gravityforms-digest.php#L392 that a CSV is still generated with the words "No new entries"; in any case, thanks for letting me know about this.

**Comment by katehcutt** [comment]
I'm having the same issue, where I receive an email that says:

Report generated at 2015-10-29 19:33:22
Contains entries from 2015-08-03 21:57:23 to 2015-10-29 19:30:14
See CSV attachment

But there is no attachment with the email. Any ideas on why no attachment is coming through?

**Comment by soulseekah** [comment]
Spam filters?

**Comment by katehcutt** [comment]
The email came into my inbox no problem, it just doesn't have the attachment. And I shouldn't have any filters that block attachments.

**Comment by soulseekah** [comment]
Set my email gennady[at]kovshenin[dot]com as one of the recipients, I'll take a look at the headers when a report comes through.

**Comment by katehcutt** [comment]
Done. Thanks!

**Comment by soulseekah** [comment]
Got your CSV

Report generated at 2015-10-29 21:49:26
Contains entries from 2015-10-29 21:34:07 to 2015-10-29 21:48:23
See CSV attachment

Were there actually entries between those times?

**Comment by katehcutt** [comment]
Did you get an actual CSV attachment? I got the email but still no attachment. Yes there were entries between those times.

**Comment by soulseekah** [comment]
No attachment, no. If you want me to solve this you'll have to send me your server credentials (FTP for example) where this is not working. Send them to my e-mail I'll take a look over the weekend.
