### ISSUE TITLE
Not receiving emails

### ISSUE THREAD

**Issue by mmohanna** [soulseekah/Gravity-Forms-Digest-Bulk-Reports#24]
Hi! I have this plugin installed, but it never actually sends the emails. I've tried with various email addresses and browsers. When the job is supposed to occur, it just switches to negative seconds ("next scheduled in -234 seconds", etc.)
![grav forms digest](https://cloud.githubusercontent.com/assets/16842653/12556158/29aff514-c34a-11e5-806c-49cb8e17bfc1.png)

**Comment by soulseekah** [comment]
Thanks for the report. Maybe your cron is not kicking off? Can you install a cron debug tool and make a screenshot of that? Maybe trigger the cron manually see what happens?

**Comment by mmohanna** [comment]
After manually running the cron job with Core Control, it says "The selected task has been run". 
![core control](https://cloud.githubusercontent.com/assets/16842653/12565581/abf5449a-c37a-11e5-9741-caa58ffa6041.png)

I noticed this "last sent lead 197" text appeared on the form settings afterward, but still no emails.

I've tried some cron debuggers, and I'm not getting any errors there.
![debug bar cron](https://cloud.githubusercontent.com/assets/16842653/12565264/5cf8a8ce-c379-11e5-80a1-237469a5c9ce.png)
![wp-cron dashboard](https://cloud.githubusercontent.com/assets/16842653/12565279/6a808f5c-c379-11e5-9320-def7f191385a.png)

**Comment by soulseekah** [comment]
Anything in the error logs? Did you check your mail log?

**Comment by mmohanna** [comment]
I just added **define('ALTERNATE_WP_CRON', true);** to wp-config.php, and everything is functioning perfectly now. It seems that HTTP loopback requests are disabled, which is causing the standard wp-cron system to fail. This is affecting all of our cron jobs, so it isn't an issue with this plugin. Thanks for the help!

**Comment by soulseekah** [comment]
Excellent, thanks for letting me know.
