### ISSUE TITLE
viewing digest export fields

### ISSUE THREAD

**Issue by adscotty** [soulseekah/Gravity-Forms-Digest-Bulk-Reports#25]
hi soulseekah, really optimistic about what your plugin might be able to do for my install. 
i don't seem to be able to view the digest export fields (see attached). 

chrome version 48.0.2564.103
gf version: 1.9.16
wordpress version: 4.4.2

![screencap](https://cloud.githubusercontent.com/assets/17188610/12997067/e002ec5c-d189-11e5-95d1-1466ff212c24.png)

**Comment by soulseekah** [comment]
This plugin doesn't provide a way to filter out specific fields via the settings. What you're seeing in the screenshot seems correct to me. Can you elaborate on what you are expecting when saying "view the digest export fields"? Thanks.

**Comment by soulseekah** [comment]
Ah, nvm, I see what you mean, I'll look into a fix against 1.9.16 after testing a bit. Hold tight.

**Comment by adscotty** [comment]
thanks - much appreciated

**Comment by soulseekah** [comment]
Couldn't reproduce on 1.9.16, are you sure you're running the latest version of this plugin? Try https://github.com/soulseekah/Gravity-Forms-Digest-Bulk-Reports/archive/master.zip

**Comment by adscotty** [comment]
that did the trick. thanks!
