### ISSUE TITLE
WordPress Cron

### ISSUE THREAD

**Issue by lukecav** [soulseekah/Gravity-Forms-Digest-Bulk-Reports#26]
Which WP cron does the digest bulk reports plugin use?

Does it just use gravityforms_cron?

**Comment by soulseekah** [comment]
I don't think I've ever heard of gravityforms_cron, what is it?

This plugin uses the regular WordPress Cron API, specifically the `wp_schedule_event` function as evidenced by this line of code: https://github.com/soulseekah/Gravity-Forms-Digest-Bulk-Reports/blob/master/gravityforms-digest/gravityforms-digest.php#L84
